games:
    resource:
        path: ../src/Game/Infrastructure/Controller
        namespace: App\Game\Infrastructure\Controller
    type: attribute
    prefix: api/games
    trailing_slash_on_root: false
    name_prefix: api_games_
players:
    resource:
        path: ../src/Player/Infrastructure/Controller
        namespace: App\Player\Infrastructure\Controller
    type: attribute
    prefix: api/players
    trailing_slash_on_root: false
    name_prefix: api_players_
scoring:
    resource:
        path: ../src/Scoring/Infrastructure/Controller
        namespace: App\Scoring\Infrastructure\Controller
    type: attribute
    prefix: api/scoring
    trailing_slash_on_root: false
    name_prefix: api_scoring_
